Readd gfz staging backup job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -554,68 +554,67 @@ build-deploy-image-mq-prod:
     - if: '$CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
       when: always
 
-# TODO: Readd the backup-gfz-staging job (we can't use it for now as the container aren't running).
-#backup-gfz-staging:
-#  stage: backup
-#  environment:
-#    name: gfz-staging
-#    url: https://rz-vm64.gfz-potsdam.de
-#  tags:
-#    - deploy
-#    - staging
-#    - gfz
-#    - shell
-#  variables:
-#    COMPOSE_PROJECT_NAME: sms-staging
-#    BACKEND_DB_PASSWORD: ${GFZ_STAGING_BACKEND_POSTGRES_PASSWORD}
-#    BACKEND_DB_USER: ${GFZ_STAGING_BACKEND_POSTGRES_USER}
-#    BACKEND_IMAGE: ${CI_REGISTRY_IMAGE}/backend:gfz-latest
-#    BACKEND_SECRET_KEY: ${GFZ_STAGING_BACKEND_SECRET}
-#    IDL_DB_PASSWORD: ${GFZ_STAGING_IDL_POSTGRES_PASSWORD}
-#    IDL_DB_USER: ${GFZ_STAGING_IDL_POSTGRES_USER}
-#    IDL_TOKEN: ${GFZ_STAGING_IDL_TOKEN}
-#    IDL_SECRET_KEY: ${GFZ_STAGING_IDL_SECRET_KEY}
-#    MINIO_ROOT_PASSWORD: ${GFZ_STAGING_MINIO_ROOT_PASSWORD}
-#    MINIO_ROOT_USER: ${GFZ_STAGING_MINIO_ROOT_USER}
-#    S3_EXTERNAL_BACKUP_ACCESS_KEY: ${GFZ_STAGING_S3_BACKUP_ACCESS_KEY}
-#    S3_EXTERNAL_BACKUP_SECRET_KEY: ${GFZ_STAGING_S3_BACKUP_SECRET_KEY}
-#    DAYS_TO_CLEANUP: 30
-#    # We want to make sure that we still have 1 GB left to do the backup
-#    # comparision value is in kb
-#    MINIMUM_STORAGE_LEFT: 1000000
-#  before_script:
-#    - *docker_login_gitlab_registry
-#  script:
-#    # clean up & remove files older than x days
-#    - mkdir -p /srv/docker/service/backend-db/backups
-#    - find /srv/docker/service/backend-db/backups -type f -mtime +${DAYS_TO_CLEANUP:-30} -exec rm {} \;
-#    - mkdir -p /srv/docker/service/idl-db/backups
-#    - find /srv/docker/service/idl-db/backups -type f -mtime +${DAYS_TO_CLEANUP:-30} -exec rm {} \;
-#    - |-
-#      if [ $(df -Pk /srv/docker/service | awk '/[0-9]%/{print $(NF-2)}') -lt ${MINIMUM_STORAGE_LEFT} ]
-#      then
-#          echo 'Not enough space left on the local file system to create the backup'
-#          exit 1
-#      fi
-#    - docker compose -f docker/deployment/gfz/staging/docker-compose.yml pull mc
-#    - docker compose -f docker/deployment/gfz/staging/docker-compose.yml exec -T idl-db pg_dump -U $IDL_DB_USER -d idl -Fc > /srv/docker/service/idl-db/backups/idl_$(date +%Y%m%d-%H%M)_${CI_COMMIT_SHORT_SHA}.dump
-#    - docker compose -f docker/deployment/gfz/staging/docker-compose.yml exec -T backend-db pg_dump -U $BACKEND_DB_USER -d backend -Fc > /srv/docker/service/backend-db/backups/backend_$(date +%Y%m%d-%H%M)_${CI_COMMIT_SHORT_SHA}.dump
-#    # The backup of the minio is handled by the backup.py script.
-#    # It sends the data to another, secured & backuped s3 bucket.
-#    - >
-#      docker compose -f docker/deployment/gfz/staging/docker-compose.yml \
-#        run -T --entrypoint '/backup.py' \
-#        --rm \
-#        -e S3_EXTERNAL_BACKUP_ACCESS_KEY=$S3_EXTERNAL_BACKUP_ACCESS_KEY \
-#        -e S3_EXTERNAL_BACKUP_SECRET_KEY=$S3_EXTERNAL_BACKUP_SECRET_KEY \
-#        mc
-#  rules:
-#    - if: '$CI_PIPELINE_SOURCE == "schedule"'
-#      when: never
-#    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
-#      when: never
-#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
-#      when: always
+backup-gfz-staging:
+  stage: backup
+  environment:
+    name: gfz-staging
+    url: https://rz-vm64.gfz-potsdam.de
+  tags:
+    - deploy
+    - staging
+    - gfz
+    - shell
+  variables:
+    COMPOSE_PROJECT_NAME: sms-staging
+    BACKEND_DB_PASSWORD: ${GFZ_STAGING_BACKEND_POSTGRES_PASSWORD}
+    BACKEND_DB_USER: ${GFZ_STAGING_BACKEND_POSTGRES_USER}
+    BACKEND_IMAGE: ${CI_REGISTRY_IMAGE}/backend:gfz-latest
+    BACKEND_SECRET_KEY: ${GFZ_STAGING_BACKEND_SECRET}
+    IDL_DB_PASSWORD: ${GFZ_STAGING_IDL_POSTGRES_PASSWORD}
+    IDL_DB_USER: ${GFZ_STAGING_IDL_POSTGRES_USER}
+    IDL_TOKEN: ${GFZ_STAGING_IDL_TOKEN}
+    IDL_SECRET_KEY: ${GFZ_STAGING_IDL_SECRET_KEY}
+    MINIO_ROOT_PASSWORD: ${GFZ_STAGING_MINIO_ROOT_PASSWORD}
+    MINIO_ROOT_USER: ${GFZ_STAGING_MINIO_ROOT_USER}
+    S3_EXTERNAL_BACKUP_ACCESS_KEY: ${GFZ_STAGING_S3_BACKUP_ACCESS_KEY}
+    S3_EXTERNAL_BACKUP_SECRET_KEY: ${GFZ_STAGING_S3_BACKUP_SECRET_KEY}
+    DAYS_TO_CLEANUP: 30
+    # We want to make sure that we still have 1 GB left to do the backup
+    # comparision value is in kb
+    MINIMUM_STORAGE_LEFT: 1000000
+  before_script:
+    - *docker_login_gitlab_registry
+  script:
+    # clean up & remove files older than x days
+    - mkdir -p /srv/docker/service/backend-db/backups
+    - find /srv/docker/service/backend-db/backups -type f -mtime +${DAYS_TO_CLEANUP:-30} -exec rm {} \;
+    - mkdir -p /srv/docker/service/idl-db/backups
+    - find /srv/docker/service/idl-db/backups -type f -mtime +${DAYS_TO_CLEANUP:-30} -exec rm {} \;
+    - |-
+      if [ $(df -Pk /srv/docker/service | awk '/[0-9]%/{print $(NF-2)}') -lt ${MINIMUM_STORAGE_LEFT} ]
+      then
+          echo 'Not enough space left on the local file system to create the backup'
+          exit 1
+      fi
+    - docker compose -f docker/deployment/gfz/staging/docker-compose.yml pull mc
+    - docker compose -f docker/deployment/gfz/staging/docker-compose.yml exec -T idl-db pg_dump -U $IDL_DB_USER -d idl -Fc > /srv/docker/service/idl-db/backups/idl_$(date +%Y%m%d-%H%M)_${CI_COMMIT_SHORT_SHA}.dump
+    - docker compose -f docker/deployment/gfz/staging/docker-compose.yml exec -T backend-db pg_dump -U $BACKEND_DB_USER -d backend -Fc > /srv/docker/service/backend-db/backups/backend_$(date +%Y%m%d-%H%M)_${CI_COMMIT_SHORT_SHA}.dump
+    # The backup of the minio is handled by the backup.py script.
+    # It sends the data to another, secured & backuped s3 bucket.
+    - >
+      docker compose -f docker/deployment/gfz/staging/docker-compose.yml \
+        run -T --entrypoint '/backup.py' \
+        --rm \
+        -e S3_EXTERNAL_BACKUP_ACCESS_KEY=$S3_EXTERNAL_BACKUP_ACCESS_KEY \
+        -e S3_EXTERNAL_BACKUP_SECRET_KEY=$S3_EXTERNAL_BACKUP_SECRET_KEY \
+        mc
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "schedule"'
+      when: never
+    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
+      when: never
+    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
+      when: always
 
 backup-gfz-prod:
   stage: backup
